variable "env" {}
variable "project_id" {}
variable "project_name" {}
variable "region" {}
variable "zone" {}
variable "gke_master_version" {}
variable "gke_node_version" {}
variable "machine_type" {}
variable "cluster_ipv4_cidr_block" {}
variable "services_ipv4_cidr_block" {}
variable "subnet_ip_cidr_range" {}
variable "node_count" {}
